# Generated by Django 3.1 on 2020-09-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydaypost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmodel',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
