# Generated by Django 3.1 on 2020-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydaypost', '0002_auto_20200924_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmodel',
            name='state',
            field=models.CharField(choices=[('សកម្ម', 'សកម្ម'), ('រួចរាល់', 'រួចរាល់'), ('ខកខាន', 'ខកខាន')], max_length=50),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='category',
            field=models.CharField(choices=[('ជីវភាព', 'ជីវភាព'), ('សាលា', 'សាលា'), ('ផ្សេងៗ', 'ផ្សេងៗ')], max_length=50),
        ),
    ]
