# Generated by Django 3.1 on 2020-09-24 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mydaypost', '0004_assignmentmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
