# Generated by Django 3.1 on 2020-09-24 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mydaypost', '0006_auto_20200925_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 24, 15, 6, 36, 878782, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
